export class AppError extends Error {
  constructor(message, statusCode = 500, code = 'INTERNAL_ERROR', details = null) {
    super(message);
    this.name = 'AppError';
    this.statusCode = statusCode;
    this.code = code;
    this.details = details;
    Error.captureStackTrace(this, this.constructor);
  }
}

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_LOCKED: 'ROOM_LOCKED',
  INVALID_ROOM_CODE: 'INVALID_ROOM_CODE',
  INVALID_DISPLAY_NAME: 'INVALID_DISPLAY_NAME',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',
  INVALID_MEDIA_SOURCE: 'INVALID_MEDIA_SOURCE',
  INVALID_MEDIA_POSITION: 'INVALID_MEDIA_POSITION',
  INVALID_PLAYBACK_RATE: 'INVALID_PLAYBACK_RATE',
  MEDIA_CONTROL_FORBIDDEN: 'MEDIA_CONTROL_FORBIDDEN',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INVALID_PERMISSION: 'INVALID_PERMISSION',
  HOST_TRANSFER_FORBIDDEN: 'HOST_TRANSFER_FORBIDDEN',
  INVALID_CHAT_MESSAGE: 'INVALID_CHAT_MESSAGE',
  CHAT_MESSAGE_TOO_LONG: 'CHAT_MESSAGE_TOO_LONG',
  INVALID_REACTION: 'INVALID_REACTION',
  NOT_ROOM_MEMBER: 'NOT_ROOM_MEMBER',
  PEER_NOT_FOUND: 'PEER_NOT_FOUND',
  PEER_NOT_IN_ROOM: 'PEER_NOT_IN_ROOM',
  INVALID_WEBRTC_SIGNAL: 'INVALID_WEBRTC_SIGNAL',
  INVALID_FILE_METADATA: 'INVALID_FILE_METADATA',
  WEBRTC_SIGNAL_FAILED: 'WEBRTC_SIGNAL_FAILED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_RECONNECT_TOKEN: 'INVALID_RECONNECT_TOKEN',
  RECONNECT_FAILED: 'RECONNECT_FAILED'
};

export const createApiResponse = (data) => ({
  success: true,
  data
});

export const createErrorResponse = (code, message, details = null) => {
  const response = {
    success: false,
    error: {
      code,
      message
    }
  };
  if (details) {
    response.error.details = details;
  }
  return response;
};
